namespace: manishboard-ns
appName: backend
deployment:
  name: manishboard-dep
  replicas: 1
  backend:
    imageName: ghcr.io/manishboard/backend
    imageTag: v1.0.0
    containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

service:
  name: manishboard-svc
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

ingress:
  name: manishboard-igrs
  className: traefik
  url: backend.manishboard.manish.kr



