namespace: manishboard-ns
appName: backend
deployment:
  name: manishboard-dep
  replicas: 1
  backend:
    imageName: ghcr.io/manishboard/backend
    imageTag: v1.0.0
    containerPort: 8080
  fluentd:
    imageName: ghcr.io/manishboard/fluentd
    imageTag: v1.0.0
    env:
      name: "FLUENTD_CONF"
      value: "fluent.conf"

volume:
  logPath:
    name: app-logs
    mountPath: /app/logs
  fluentdConfigPath:
    name: fluentd-config
    mountPath: /fluentd/etc

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

secrets:
  github: ghcr-secret
  ssl: manishboard-tls

service:
  name: manishboard-svc
  type: LoadBalancer
  port: 80
  targetPort: 8080
  protocol: TCP

ingress:
  name: manishboard-igrs
  className: traefik
  url: backend.manishboard.manish.kr

configMap:
  name: fluentd-config



