namespace: manishboard-ns
appName: backend
deployment:
  name: manishboard-dep
  replicas: 2
  backend:
    imageName: ghcr.io/manishboard/backend
    imageTag: latest
    containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

docker:
  creds: ghcr-logins

service:
  name: manishboard-svc
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP

ingress:
  name: manishboard-igrs
  className: traefik
  url: backend.manishboard.manish.kr

certificate:
  name: manishboard-tls-cert
  secretName: manishboard-tls-secret


